# Generated by Django 4.1.3 on 2022-11-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='author',
        ),
    ]
