# Generated by Django 4.1.3 on 2022-11-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Movie Budget'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(default=0, null=True, verbose_name='IMDB Rating'),
        ),
    ]
