# Generated by Django 4.1.3 on 2022-11-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_budget_alter_movie_imdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5, null=True, verbose_name='Movie Budget'),
        ),
    ]
