# Generated by Django 4.1.3 on 2022-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True, verbose_name='Movie Budget'),
        ),
    ]
