# Generated by Django 4.1.3 on 2022-11-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='Published Date'),
        ),
    ]
