# Generated by Django 4.1.3 on 2022-11-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected')], default='R', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='movie.movie'),
        ),
    ]
