# Generated by Django 4.1.3 on 2022-11-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_actor_movie_remove_actor_role_actor_movies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='role',
            field=models.CharField(choices=[('AR', 'Actor'), ('DR', 'Director')], default='AR', max_length=2, verbose_name='Role'),
        ),
    ]
